// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VRSimulator.Api.Persistence;

#nullable disable

namespace VRSimulator.Api.Persistence.Migrations
{
    [DbContext(typeof(TrainingDbContext))]
    [Migration("20260626115329_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.36")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("VRSimulator.Api.Persistence.Entities.AuthSessionEntity", b =>
                {
                    b.Property<string>("AccessToken")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("AccessToken");

                    b.HasIndex("UserId");

                    b.ToTable("AuthSessions", (string)null);
                });

            modelBuilder.Entity("VRSimulator.Api.Persistence.Entities.CertificateEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CertificateNumber")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("IssuedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<DateTimeOffset>("ValidUntil")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("WorkerId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CertificateNumber")
                        .IsUnique();

                    b.HasIndex("CourseId");

                    b.HasIndex("WorkerId");

                    b.ToTable("Certificates", (string)null);
                });

            modelBuilder.Entity("VRSimulator.Api.Persistence.Entities.CompanyEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Companies", (string)null);
                });

            modelBuilder.Entity("VRSimulator.Api.Persistence.Entities.CourseEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("DescriptionEn")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("DescriptionSr")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("nvarchar(180)");

                    b.Property<string>("NameSr")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("nvarchar(180)");

                    b.Property<int>("PassScore")
                        .HasColumnType("int");

                    b.Property<int>("ValidityMonths")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Courses", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("c3d3b41f-3017-4861-9d09-dbf349b1df43"),
                            Code = "fire-protection",
                            DescriptionEn = "Risk recognition, evacuation, equipment selection, and correct response.",
                            DescriptionSr = "Prepoznavanje rizika, evakuacija, izbor opreme i pravilno reagovanje.",
                            NameEn = "Fire protection",
                            NameSr = "Protivpozarna zastita",
                            PassScore = 80,
                            ValidityMonths = 12
                        },
                        new
                        {
                            Id = new Guid("3a37e5bb-b46c-4d41-aeca-f5ad8a9c27e5"),
                            Code = "radioactive-materials",
                            DescriptionEn = "Protective equipment, exposure control, and procedural checks.",
                            DescriptionSr = "Zastitna oprema, kontrola izlozenosti i proceduralne provere.",
                            NameEn = "Radioactive material handling",
                            NameSr = "Upravljanje radioaktivnim materijalima",
                            PassScore = 80,
                            ValidityMonths = 12
                        },
                        new
                        {
                            Id = new Guid("1f331493-79d8-42c5-b3d0-8c0b11330f27"),
                            Code = "chemical-waste",
                            DescriptionEn = "Classification, labeling, storage, and spill response.",
                            DescriptionSr = "Klasifikacija, obelezavanje, skladistenje i reakcija na prosipanje.",
                            NameEn = "Chemical waste management",
                            NameSr = "Upravljanje hemijskim otpadom",
                            PassScore = 80,
                            ValidityMonths = 12
                        },
                        new
                        {
                            Id = new Guid("79c6aa17-f058-4329-9fd5-8ec279cc873d"),
                            Code = "construction-waste",
                            DescriptionEn = "Material sorting, safe work, and waste flow tracking.",
                            DescriptionSr = "Razdvajanje materijala, bezbedan rad i pracenje tokova otpada.",
                            NameEn = "Construction waste management",
                            NameSr = "Upravljanje gradjevinskim otpadom",
                            PassScore = 80,
                            ValidityMonths = 12
                        },
                        new
                        {
                            Id = new Guid("4cce62e1-7849-4a1e-93dd-796043ebd18c"),
                            Code = "electronic-waste",
                            DescriptionEn = "Sorting devices, batteries, cables, and sensitive components.",
                            DescriptionSr = "Sortiranje uredjaja, baterija, kablova i osetljivih komponenti.",
                            NameEn = "Electronic waste management",
                            NameSr = "Upravljanje elektronskim otpadom",
                            PassScore = 80,
                            ValidityMonths = 12
                        },
                        new
                        {
                            Id = new Guid("30b016e2-cbe6-4fab-a6f5-6e3f47ee4cc8"),
                            Code = "biomedical-waste",
                            DescriptionEn = "Separation, packaging, and temporary storage of healthcare waste.",
                            DescriptionSr = "Razdvajanje, pakovanje i privremeno skladistenje zdravstvenog otpada.",
                            NameEn = "Biomedical waste management",
                            NameSr = "Upravljanje biomedicinskim otpadom",
                            PassScore = 80,
                            ValidityMonths = 12
                        });
                });

            modelBuilder.Entity("VRSimulator.Api.Persistence.Entities.CourseScenarioEntity", b =>
                {
                    b.Property<Guid>("CourseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ScenarioId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("CourseId", "ScenarioId");

                    b.HasIndex("ScenarioId");

                    b.ToTable("CourseScenarios", (string)null);

                    b.HasData(
                        new
                        {
                            CourseId = new Guid("c3d3b41f-3017-4861-9d09-dbf349b1df43"),
                            ScenarioId = new Guid("c77fe939-98ee-4ca5-9f61-0d8f9d31f2b2")
                        },
                        new
                        {
                            CourseId = new Guid("3a37e5bb-b46c-4d41-aeca-f5ad8a9c27e5"),
                            ScenarioId = new Guid("0d91384d-6c32-4f84-89c6-2bc378d01c18")
                        },
                        new
                        {
                            CourseId = new Guid("1f331493-79d8-42c5-b3d0-8c0b11330f27"),
                            ScenarioId = new Guid("bf90d0a8-f907-40fc-9450-bc6ec237bcb9")
                        },
                        new
                        {
                            CourseId = new Guid("79c6aa17-f058-4329-9fd5-8ec279cc873d"),
                            ScenarioId = new Guid("ffdb0364-47e2-4f4d-96b3-38675ba0938a")
                        },
                        new
                        {
                            CourseId = new Guid("4cce62e1-7849-4a1e-93dd-796043ebd18c"),
                            ScenarioId = new Guid("c391aa43-b3c6-4876-93db-fca11143e2b5")
                        },
                        new
                        {
                            CourseId = new Guid("30b016e2-cbe6-4fab-a6f5-6e3f47ee4cc8"),
                            ScenarioId = new Guid("2a2d3685-1488-4d53-bd78-b82bb3a4c0d0")
                        });
                });

            modelBuilder.Entity("VRSimulator.Api.Persistence.Entities.EnrollmentEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("DurationMinutes")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("EnrolledAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("Score")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<Guid>("WorkerId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.HasIndex("WorkerId");

                    b.ToTable("Enrollments", (string)null);
                });

            modelBuilder.Entity("VRSimulator.Api.Persistence.Entities.TrainingScenarioEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("DescriptionEn")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("DescriptionSr")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("EstimatedMinutes")
                        .HasColumnType("int");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("nvarchar(180)");

                    b.Property<string>("NameSr")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("nvarchar(180)");

                    b.Property<string>("RiskCategory")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("TrainingScenarios", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("c77fe939-98ee-4ca5-9f61-0d8f9d31f2b2"),
                            Code = "fire-protection",
                            DescriptionEn = "Risk recognition, evacuation, equipment selection, and correct response.",
                            DescriptionSr = "Prepoznavanje rizika, evakuacija, izbor opreme i pravilno reagovanje.",
                            EstimatedMinutes = 35,
                            NameEn = "Fire protection",
                            NameSr = "Protivpozarna zastita",
                            RiskCategory = "Safety"
                        },
                        new
                        {
                            Id = new Guid("0d91384d-6c32-4f84-89c6-2bc378d01c18"),
                            Code = "radioactive-materials",
                            DescriptionEn = "Protective equipment, exposure control, and procedural checks.",
                            DescriptionSr = "Zastitna oprema, kontrola izlozenosti i proceduralne provere.",
                            EstimatedMinutes = 45,
                            NameEn = "Radioactive material handling",
                            NameSr = "Upravljanje radioaktivnim materijalima",
                            RiskCategory = "Hazardous materials"
                        },
                        new
                        {
                            Id = new Guid("bf90d0a8-f907-40fc-9450-bc6ec237bcb9"),
                            Code = "chemical-waste",
                            DescriptionEn = "Classification, labeling, storage, and spill response.",
                            DescriptionSr = "Klasifikacija, obelezavanje, skladistenje i reakcija na prosipanje.",
                            EstimatedMinutes = 40,
                            NameEn = "Chemical waste management",
                            NameSr = "Upravljanje hemijskim otpadom",
                            RiskCategory = "Waste management"
                        },
                        new
                        {
                            Id = new Guid("ffdb0364-47e2-4f4d-96b3-38675ba0938a"),
                            Code = "construction-waste",
                            DescriptionEn = "Material sorting, safe work, and waste flow tracking.",
                            DescriptionSr = "Razdvajanje materijala, bezbedan rad i pracenje tokova otpada.",
                            EstimatedMinutes = 30,
                            NameEn = "Construction waste management",
                            NameSr = "Upravljanje gradjevinskim otpadom",
                            RiskCategory = "Waste management"
                        },
                        new
                        {
                            Id = new Guid("c391aa43-b3c6-4876-93db-fca11143e2b5"),
                            Code = "electronic-waste",
                            DescriptionEn = "Sorting devices, batteries, cables, and sensitive components.",
                            DescriptionSr = "Sortiranje uredjaja, baterija, kablova i osetljivih komponenti.",
                            EstimatedMinutes = 35,
                            NameEn = "Electronic waste management",
                            NameSr = "Upravljanje elektronskim otpadom",
                            RiskCategory = "Waste management"
                        },
                        new
                        {
                            Id = new Guid("2a2d3685-1488-4d53-bd78-b82bb3a4c0d0"),
                            Code = "biomedical-waste",
                            DescriptionEn = "Separation, packaging, and temporary storage of healthcare waste.",
                            DescriptionSr = "Razdvajanje, pakovanje i privremeno skladistenje zdravstvenog otpada.",
                            EstimatedMinutes = 40,
                            NameEn = "Biomedical waste management",
                            NameSr = "Upravljanje biomedicinskim otpadom",
                            RiskCategory = "Healthcare safety"
                        });
                });

            modelBuilder.Entity("VRSimulator.Api.Persistence.Entities.UserEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("nvarchar(254)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<byte[]>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varbinary(128)");

                    b.Property<byte[]>("PasswordSalt")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varbinary(64)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("VRSimulator.Api.Persistence.Entities.WorkerEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<string>("EmployeeNumber")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId", "EmployeeNumber")
                        .IsUnique();

                    b.ToTable("Workers", (string)null);
                });

            modelBuilder.Entity("VRSimulator.Api.Persistence.Entities.AuthSessionEntity", b =>
                {
                    b.HasOne("VRSimulator.Api.Persistence.Entities.UserEntity", "User")
                        .WithMany("Sessions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("VRSimulator.Api.Persistence.Entities.CertificateEntity", b =>
                {
                    b.HasOne("VRSimulator.Api.Persistence.Entities.CourseEntity", "Course")
                        .WithMany()
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VRSimulator.Api.Persistence.Entities.WorkerEntity", "Worker")
                        .WithMany("Certificates")
                        .HasForeignKey("WorkerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Worker");
                });

            modelBuilder.Entity("VRSimulator.Api.Persistence.Entities.CourseScenarioEntity", b =>
                {
                    b.HasOne("VRSimulator.Api.Persistence.Entities.CourseEntity", "Course")
                        .WithMany("CourseScenarios")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VRSimulator.Api.Persistence.Entities.TrainingScenarioEntity", "Scenario")
                        .WithMany("CourseScenarios")
                        .HasForeignKey("ScenarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Scenario");
                });

            modelBuilder.Entity("VRSimulator.Api.Persistence.Entities.EnrollmentEntity", b =>
                {
                    b.HasOne("VRSimulator.Api.Persistence.Entities.CourseEntity", "Course")
                        .WithMany()
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VRSimulator.Api.Persistence.Entities.WorkerEntity", "Worker")
                        .WithMany("Enrollments")
                        .HasForeignKey("WorkerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Worker");
                });

            modelBuilder.Entity("VRSimulator.Api.Persistence.Entities.UserEntity", b =>
                {
                    b.HasOne("VRSimulator.Api.Persistence.Entities.CompanyEntity", "Company")
                        .WithMany("Users")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("VRSimulator.Api.Persistence.Entities.WorkerEntity", b =>
                {
                    b.HasOne("VRSimulator.Api.Persistence.Entities.CompanyEntity", "Company")
                        .WithMany("Workers")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("VRSimulator.Api.Persistence.Entities.CompanyEntity", b =>
                {
                    b.Navigation("Users");

                    b.Navigation("Workers");
                });

            modelBuilder.Entity("VRSimulator.Api.Persistence.Entities.CourseEntity", b =>
                {
                    b.Navigation("CourseScenarios");
                });

            modelBuilder.Entity("VRSimulator.Api.Persistence.Entities.TrainingScenarioEntity", b =>
                {
                    b.Navigation("CourseScenarios");
                });

            modelBuilder.Entity("VRSimulator.Api.Persistence.Entities.UserEntity", b =>
                {
                    b.Navigation("Sessions");
                });

            modelBuilder.Entity("VRSimulator.Api.Persistence.Entities.WorkerEntity", b =>
                {
                    b.Navigation("Certificates");

                    b.Navigation("Enrollments");
                });
#pragma warning restore 612, 618
        }
    }
}
